//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedWebService
{
    using System;
    using Application;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Configuration;
    using SqlAdapter;
    using Application.Users;
    using HttpAdapter.Users;
    using SqlAdapter.Users;
    using Application.Posts;
    using HttpAdapter.Posts;
    using SqlAdapter.Posts;
    using Application.Users.Hooks;
    
    
    public class GeneratedDependencies
    {
        
        public static void ConfigureGeneratedServices(IServiceCollection collection, IConfiguration configuration)
        {
            collection.AddDbContext<EventStoreContext>(option => option.UseSqlite(configuration.GetConnectionString("EventStoreDatabase")));
            collection.AddTransient<EventStore>();
            collection.AddTransient<IEventStoreRepository, EventStoreRepository>();
            collection.AddMvc().AddApplicationPart(typeof(UserController).Assembly);
            collection.AddTransient<IUserRepository, UserRepository>();
            collection.AddTransient<UserCommandHandler>();
            collection.AddTransient<IPostRepository, PostRepository>();
            collection.AddTransient<PostCommandHandler>();
            collection.AddTransient<SendPasswordMailHook>();
        }
    }
}
