//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Users.Hooks
{
    using System;
    using System.Collections.Generic;
    using Domain.Users;
    using Domain;
    
    
    public partial class SendPasswordMailHook
    {
        
        private HookResult Execute(UserCreateEvent domainEvent)
        {
            if (domainEvent.User.Age > 100) return HookResult.ErrorResult(new List<string>{ "Fehler fuer test"});
            var newUserAge = domainEvent.User.Age + 10;
            var domainEventBases = new List<DomainEventBase>();
            domainEventBases.Add(new UserUpdateAgeEvent(newUserAge, Guid.NewGuid()));
            return HookResult.OkResult(); }
    }
}
