//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;
using Domain.Posts;
using GraphQL;
using GraphQL.Types;
using Newtonsoft.Json;
using SqlAdapter;

namespace HttpAdapter.Users
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Domain.Users;
    using Microsoft.AspNetCore.Mvc;
    using Application.Users;

    [Route("api/usersgraphl")]
    public class UserGraphlController : Controller
    {
        private readonly EventStoreContext _context;

        public UserCommandHandler Handler { get; private set; }
        
        public UserGraphlController(UserCommandHandler Handler, EventStoreContext context)
        {
            _context = context;
            this.Handler = Handler;
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
        {
            var schema = new Schema { Query = new ServiceQuery() };

            var result = await new DocumentExecuter().ExecuteAsync(_ =>
            {
                _.Schema = schema;
                _.Query = query.Query;

            }).ConfigureAwait(false);

            if (result.Errors?.Count > 0)
            {
                return BadRequest();
            }

            return Ok(result);
        }
    }

    public class UserType : ObjectGraphType<User>
    {
        public UserType()
        {
            Field(x => x.ID).Description("The Id of the Droid.");
            Field(x => x.Name, nullable: true).Description("The name of the Droid.");
        }
    }

    public class ServiceQuery : ObjectGraphType
    {
        public ServiceQuery()
        {
            Field<UserType>(
                "user",
                resolve: context => User.Create(new UserCreateCommand("Simon", 15)).CreatedEntity
            );
        }
    }

    public class GraphQLQuery
    {
        public string OperationName { get; set; }
        public string NamedQuery { get; set; }
        public string Query { get; set; }
        public string Variables { get; set; }
    }
}
