// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using SqlAdapter;
using System;

namespace SqlAdapter.Migrations
{
    [DbContext(typeof(EventStoreContext))]
    [Migration("20180513185956_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Domain.DomainEventBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<Guid>("EntityId");

                    b.HasKey("Id");

                    b.ToTable("EventHistory");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DomainEventBase");
                });

            modelBuilder.Entity("Domain.Posts.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<string>("Title");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Posts.PostCreateEvent", b =>
                {
                    b.HasBaseType("Domain.DomainEventBase");


                    b.ToTable("PostCreateEvent");

                    b.HasDiscriminator().HasValue("PostCreateEvent");
                });

            modelBuilder.Entity("Domain.Posts.PostUpdateTitleEvent", b =>
                {
                    b.HasBaseType("Domain.DomainEventBase");

                    b.Property<string>("Title");

                    b.ToTable("PostUpdateTitleEvent");

                    b.HasDiscriminator().HasValue("PostUpdateTitleEvent");
                });

            modelBuilder.Entity("Domain.Users.UserAddPostEvent", b =>
                {
                    b.HasBaseType("Domain.DomainEventBase");

                    b.Property<Guid>("Deleted");

                    b.Property<Guid>("PostId");

                    b.ToTable("UserAddPostEvent");

                    b.HasDiscriminator().HasValue("UserAddPostEvent");
                });

            modelBuilder.Entity("Domain.Users.UserCreateEvent", b =>
                {
                    b.HasBaseType("Domain.DomainEventBase");


                    b.ToTable("UserCreateEvent");

                    b.HasDiscriminator().HasValue("UserCreateEvent");
                });

            modelBuilder.Entity("Domain.Users.UserUpdateAgeEvent", b =>
                {
                    b.HasBaseType("Domain.DomainEventBase");

                    b.Property<int>("Age");

                    b.ToTable("UserUpdateAgeEvent");

                    b.HasDiscriminator().HasValue("UserUpdateAgeEvent");
                });

            modelBuilder.Entity("Domain.Users.UserUpdateNameEvent", b =>
                {
                    b.HasBaseType("Domain.DomainEventBase");

                    b.Property<string>("Name");

                    b.ToTable("UserUpdateNameEvent");

                    b.HasDiscriminator().HasValue("UserUpdateNameEvent");
                });

            modelBuilder.Entity("Domain.Posts.Post", b =>
                {
                    b.HasOne("Domain.Users.User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
